Added Provide-Capability and resolution=optional
ngriffin7a/portals-pluto pull request #4
Opened 2016-12-15 18:12 UTC by vsingleton

per suggestions from Ray Auge and Neil Griffin

2016-12-15 18:23 UTC, rotty3000 requested changes

2016-12-15 18:23 UTC, rotty3000 commented on portlet-api/pom.xml
> +                        javax.enterprise.context;version="[1.1,2)";resolution:=optional,
I would probably remove the manual package import version here.

2016-12-15 18:23 UTC, rotty3000 commented on portlet-api/pom.xml
> +                     <Provide-Capability>osgi.contract; osgi.contract=JavaPortlet; version:List&lt;Version&gt;="3,2,1"; uses:="javax.enterprise.context,javax.inject,javax.servlet,javax.servlet.http,j
The uses here should include the packages exported by the spec API rather than the packages used by the API.

2016-12-15 19:11 UTC, rotty3000 commented on portlet-api/pom.xml
> +                     <Provide-Capability>osgi.contract; osgi.contract=JavaPortlet; version:List&lt;Version&gt;="3,2,1"; uses:="javax.enterprise.context,javax.inject,javax.servlet,javax.servlet.http,j
To be clear, don't include the packages used by the API... only include the packages provided (exported) by the API.

2016-12-15 19:12 UTC, rotty3000 commented on portlet-api/pom.xml
> +                     <Provide-Capability>osgi.contract; osgi.contract=JavaPortlet; version:List&lt;Version&gt;="3,2,1"; uses:="javax.enterprise.context,javax.inject,javax.servlet,javax.servlet.http,j
The other packages used by the API which are not part of the API should already be covered by the uses clauses generated by bnd on the Export-Packages directive.

2016-12-15 19:15 UTC, vsingleton commented on portlet-api/pom.xml
> +                     <Provide-Capability>osgi.contract; osgi.contract=JavaPortlet; version:List&lt;Version&gt;="3,2,1"; uses:="javax.enterprise.context,javax.inject,javax.servlet,javax.servlet.http,j
I think i have it correct now ... could you check again?  Thanks.

2016-12-15 19:26 UTC, rotty3000 commented
May I ask you to dump the generated manifest here so I can view it before I give the thumbs up?

2016-12-15 20:23 UTC, vsingleton commented
Absolutely.  Here it is:
https://liferayeng.slack.com/files/vernon.singleton/F3EPC03TK/dump_of_the_generated_manifest.txt

2016-12-15 20:26 UTC, rotty3000 commented
FYI, I'm putting it here for posterity:
```
$ bnd print portlet-api/target/portlet-api-3.0-SNAPSHOT.jar 
[MANIFEST portlet-api-3.0-SNAPSHOT]
Bnd-LastModified                         1481828987586                           
Build-Jdk                                1.7.0_79                                
Built-By                                 apple                                   
Bundle-Description                       The Java Portlet API version 3.0 developed by the Java Community Process JSR-362 Expert Group.
Bundle-DocURL                            http://portals.apache.org/pluto/portlet-api
Bundle-License                           http://www.apache.org/licenses/LICENSE-2.0.txt
Bundle-ManifestVersion                   2                                       
Bundle-Name                              Java Portlet API V3.0                   
Bundle-SymbolicName                      javax.portlet.api                       
Bundle-Vendor                            The Apache Software Foundation          
Bundle-Version                           3.0.0.SNAPSHOT                          
Created-By                               Apache Maven Bundle Plugin              
Export-Package                           javax.portlet;uses:="javax.portlet.annotations,javax.servlet,javax.servlet.http,javax.xml.namespace,org.w3c.dom";version="3.0.0",javax.portlet.annotations;uses:="javax.enterprise.context,javax.inject";version="3.0.0",javax.portlet.filter;uses:="javax.portlet,javax.portlet.annotations,javax.servlet,javax.servlet.http,javax.xml.namespace,org.w3c.dom";version="3.0.0"
Implementation-Title                     Java Portlet API V3.0                   
Implementation-Version                   3.0-SNAPSHOT                            
Import-Package                           javax.enterprise.context;resolution:=optional;version="[1.1,2)",javax.inject;resolution:=optional,javax.portlet,javax.portlet.annotations,javax.servlet,javax.servlet.http,javax.xml.namespace,org.w3c.dom
Manifest-Version                         1.0                                     
Provide-Capability                       osgi.contract;osgi.contract=JavaPortlet;version:List<Version>="3,2,1";uses:="javax.portlet,javax.portlet.annotations,javax.portlet.filter"
Require-Capability                       osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.7))"
Specification-Version                    3.0-SNAPSHOT                            
Tool                                     Bnd-3.2.0.201605172007                  

[IMPEXP]
Import-Package
  javax.enterprise.context               {resolution:=optional, version=[1.1,2)}
  javax.inject                           {resolution:=optional}
  javax.portlet                          
  javax.portlet.annotations              
  javax.servlet                          
  javax.servlet.http                     
  javax.xml.namespace                    
  org.w3c.dom                            
Export-Package
  javax.portlet                          {version=3.0.0}
  javax.portlet.annotations              {version=3.0.0}
  javax.portlet.filter                   {version=3.0.0}
```

2016-12-15 21:55 UTC, rotty3000 commented
One comment I got back is that it would be friendlier if the bsn (Bundle-SymbolicName) matched the artifactId.

2016-12-15 23:28 UTC, vsingleton commented
Great feedback.  Just made the change.  Here is the latest manifest:
```
$ bnd print portlet-api/target/portlet-api-3.0-SNAPSHOT.jar 
[MANIFEST portlet-api-3.0-SNAPSHOT]
Bnd-LastModified                         1481843772468                           
Build-Jdk                                1.7.0_79                                
Built-By                                 apple                                   
Bundle-Description                       The Java Portlet API version 3.0 developed by the Java Community Process JSR-362 Expert Group.
Bundle-DocURL                            http://portals.apache.org/pluto/portlet-api
Bundle-License                           http://www.apache.org/licenses/LICENSE-2.0.txt
Bundle-ManifestVersion                   2                                       
Bundle-Name                              Java Portlet API V3.0                   
Bundle-SymbolicName                      portlet-api                             
Bundle-Vendor                            The Apache Software Foundation          
Bundle-Version                           3.0.0.SNAPSHOT                          
Created-By                               Apache Maven Bundle Plugin              
Export-Package                           javax.portlet;uses:="javax.portlet.annotations,javax.servlet,javax.servlet.http,javax.xml.namespace,org.w3c.dom";version="3.0.0",javax.portlet.annotations;uses:="javax.enterprise.context,javax.inject";version="3.0.0",javax.portlet.filter;uses:="javax.portlet,javax.portlet.annotations,javax.servlet,javax.servlet.http,javax.xml.namespace,org.w3c.dom";version="3.0.0"
Implementation-Title                     Java Portlet API V3.0                   
Implementation-Version                   3.0-SNAPSHOT                            
Import-Package                           javax.enterprise.context;resolution:=optional;version="[1.1,2)",javax.inject;resolution:=optional,javax.portlet,javax.portlet.annotations,javax.servlet,javax.servlet.http,javax.xml.namespace,org.w3c.dom
Manifest-Version                         1.0                                     
Provide-Capability                       osgi.contract;osgi.contract=JavaPortlet;version:List<Version>="3,2,1";uses:="javax.portlet,javax.portlet.annotations,javax.portlet.filter"
Require-Capability                       osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.7))"
Specification-Version                    3.0-SNAPSHOT                            
Tool                                     Bnd-3.2.0.201605172007                  

[IMPEXP]
Import-Package
  javax.enterprise.context               {resolution:=optional, version=[1.1,2)}
  javax.inject                           {resolution:=optional}
  javax.portlet                          
  javax.portlet.annotations              
  javax.servlet                          
  javax.servlet.http                     
  javax.xml.namespace                    
  org.w3c.dom                            
Export-Package
  javax.portlet                          {version=3.0.0}
  javax.portlet.annotations              {version=3.0.0}
  javax.portlet.filter                   {version=3.0.0}```

2016-12-16 14:32 UTC, rotty3000 commented
Yup, it all looks good!

2016-12-16 20:37 UTC, ngriffin7a commented
Merged. Thank you.

2016-12-16 20:37 UTC, closed without merging